### ISSUE TITLE
If pigpiod isn't running, DHT11 polling fails cryptically

### ISSUE THREAD

**Issue by gboling** [gboling/Rpi-WLcam#3]
```
Traceback (most recent call last):
  File "./Rpi-WLcam.py", line 169, in MOTION
    recordImage2(day_dir)
  File "./Rpi-WLcam.py", line 120, in recordImage2
    dht_err, temp_c, hum_pct = tempHumidity()
  File "./Rpi-WLcam.py", line 101, in tempHumidity
    dht_list = dhtwrapper.read_dht(DHT_PIN)
  File "/home/pi/Rpi-WLcam/dhtwrapper.py", line 16, in read_dht
    dht_list = map(float, dl.split(' '))
ValueError: could not convert string to float: 
```

**Comment by gboling** [comment]
```
Traceback (most recent call last):
  File "./Rpi-WLcam.py", line 169, in MOTION
    recordImage2(day_dir)
  File "./Rpi-WLcam.py", line 120, in recordImage2
    dht_err, temp_c, hum_pct = tempHumidity()
  File "./Rpi-WLcam.py", line 101, in tempHumidity
    dht_list = dhtwrapper.read_dht(DHT_PIN)
  File "/home/pi/Rpi-WLcam/dhtwrapper.py", line 16, in read_dht
    dht_list = map(float, dl.split(' '))
ValueError: could not convert string to float: 
```

**Comment by gboling** [comment]
Switching to Adafruit_DHT library fixes this issue.
